/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/HyZucgOycb3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import Link from "next/link"

export function Component() {
  return (
    <div className="flex flex-col items-center justify-center h-screen bg-white dark:bg-gray-950">
      <div className="bg-white p-8 rounded-lg shadow-lg w-full max-w-md dark:bg-gray-950">
        <div className="flex flex-col items-center justify-center gap-8 text-2xl">
          <div className="flex items-center gap-4">
            <Avatar>
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div className="text-lg font-semibold">John Doe</div>
          </div>
        </div>
        <div className="flex flex-col items-center gap-6">
          <div className="flex flex-col items-center gap-2">
            <div className="text-3xl font-bold">Your Score</div>
            <div className="text-6xl font-bold">120</div>
            <div className="flex items-center gap-2">
              <TrophyIcon className="w-6 h-6 fill-gray-900 dark:fill-gray-50" />
              <span className="text-sm font-medium text-gray-900 dark:text-gray-50">New Personal Best</span>
            </div>
          </div>
          <div className="grid grid-cols-3 gap-4">
            <div className="flex flex-col items-center gap-1">
              <ClockIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
              <div className="text-sm font-medium">60 WPM</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">New Personal Best</div>
            </div>
            <div className="flex flex-col items-center gap-1">
              <XIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
              <div className="text-sm font-medium">5 Mistakes</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">New Personal Best</div>
            </div>
            <div className="flex flex-col items-center gap-1">
              <PercentIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
              <div className="text-sm font-medium">95% Accuracy</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">New Personal Best</div>
            </div>
          </div>
        </div>
        <div className="mt-8 border-t pt-6">
          <div className="grid grid-cols-2 gap-4">
            <div className="flex flex-col items-center gap-2">
              <div className="flex items-center gap-2">
                <Avatar>
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>JS</AvatarFallback>
                </Avatar>
                <span>John Smith</span>
              </div>
              <div className="text-2xl font-bold">105</div>
              <div className="flex items-center gap-2">
                <Badge variant="success">Win</Badge>
                <Badge variant="destructive">Lose</Badge>
              </div>
            </div>
            <div className="flex flex-col items-center gap-2">
              <div className="text-sm font-medium">Friend's Score</div>
              <div className="text-2xl font-bold">95</div>
              <div className="flex items-center gap-2">
                <TrophyIcon className="w-5 h-5 fill-gray-900 dark:fill-gray-50" />
                <span className="text-xs text-gray-900 dark:text-gray-50">Personal Best</span>
              </div>
            </div>
          </div>
        </div>
        <div className="mt-8 flex justify-center gap-4">
          <Link
            href="#"
            className="inline-flex items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
            prefetch={false}
          >
            ホームへ戻る
          </Link>
          <Link
            href="#"
            className="inline-flex items-center justify-center rounded-md border border-gray-200 bg-white px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300"
            prefetch={false}
          >
            もう一度遊ぶ
          </Link>
        </div>
      </div>
    </div>
  )
}

function ClockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}


function PercentIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="19" x2="5" y1="5" y2="19" />
      <circle cx="6.5" cy="6.5" r="2.5" />
      <circle cx="17.5" cy="17.5" r="2.5" />
    </svg>
  )
}


function TrophyIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6" />
      <path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18" />
      <path d="M4 22h16" />
      <path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22" />
      <path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22" />
      <path d="M18 2H6v7a6 6 0 0 0 12 0V2Z" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
